# Docker
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'ascdevopsoh'
    appName: 'openhacky708ijk5userjava'
    deployToSlotOrASE: true
    resourceGroupName: 'openhacky708ijk5rg'
    slotName: 'staging'
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'apis/user-java/Dockerfile'
        tags: |
          $(tag)